"""Updater for managed sections in README files."""

import re
from pathlib import Path

from ..constants import (
    MARKER_COMMENT_MD_BEGIN,
    MARKER_COMMENT_MD_END,
    MARKER_COMMENT_RST_BEGIN,
    MARKER_COMMENT_RST_END,
    MARKER_README_MAIN_END,
    MARKER_README_MAIN_START,
    MARKER_README_TOC_END,
    MARKER_README_TOC_START,
    MARKER_README_TOCFULL_END,
    MARKER_README_TOCFULL_START,
)
from .exceptions import FileOperationError
from .toc import create_toc_generator


class ReadmeUpdater:
    """Update README files with generated content."""

    def __init__(
        self,
        format_type: str = "markdown",
        start_marker: str = MARKER_README_MAIN_START,
        end_marker: str = MARKER_README_MAIN_END,
        toc_bullet_style: str | None = None,
    ):
        self.format_type = format_type.lower()

        # Set format-specific comment markers
        if self.format_type == "rst":
            comment_begin = MARKER_COMMENT_RST_BEGIN
            comment_end = MARKER_COMMENT_RST_END
        else:
            comment_begin = MARKER_COMMENT_MD_BEGIN
            comment_end = MARKER_COMMENT_MD_END

        self.start_marker = f"{comment_begin}{start_marker}{comment_end}"
        self.end_marker = f"{comment_begin}{end_marker}{comment_end}"

        # TOC markers
        self.toc_start_marker = f"{comment_begin}{MARKER_README_TOC_START}{comment_end}"
        self.toc_end_marker = f"{comment_begin}{MARKER_README_TOC_END}{comment_end}"

        # TOC-FULL markers (whole-document table of contents)
        self.tocfull_start_marker = (
            f"{comment_begin}{MARKER_README_TOCFULL_START}{comment_end}"
        )
        self.tocfull_end_marker = (
            f"{comment_begin}{MARKER_README_TOCFULL_END}{comment_end}"
        )

        # TOC generator for the specified format
        self.toc_generator = create_toc_generator(
            format_type=self.format_type, bullet_style=toc_bullet_style
        )

    def update_readme(self, readme_path: Path, new_content: str) -> bool:
        """Update content between markers in README file."""

        try:
            updated_content = self._get_updated_content(readme_path, new_content)
            readme_path.write_text(updated_content, encoding="utf-8", newline="\n")
            return True

        except Exception as e:
            raise FileOperationError(f"Failed to update README: {e}")

    def _get_updated_content(self, readme_path: Path, new_content: str) -> str:
        """Get the updated content without writing to file."""
        if readme_path.exists():
            content = readme_path.read_text(encoding="utf-8")
            # Update main content
            content = self._replace_between_markers(
                content, new_content, self.start_marker, self.end_marker
            )
            # Update TOC if markers are present
            content = self._update_toc_section(content)
            # Update TOC-FULL if markers are present
            content = self._update_tocfull_section(content)
            return content
        else:
            # Create new README with template
            return self._create_new_readme(new_content, readme_path.parent.name)

    def _replace_between_markers(
        self, content: str, new_content: str, start_marker: str, end_marker: str
    ) -> str:
        """Replace content between markers."""

        if start_marker not in content or end_marker not in content:
            # Add markers and content at the end
            return content + f"\n\n{start_marker}\n{new_content}\n{end_marker}\n"

        # Replace content between existing markers
        pattern = f"({re.escape(start_marker)}).*?({re.escape(end_marker)})"
        return re.sub(
            pattern,
            lambda match: f"{match.group(1)}\n{new_content}\n{match.group(2)}",
            content,
            flags=re.DOTALL,
        )

    def _update_toc_section(self, content: str) -> str:
        """Update TOC section if markers are present, using only main content."""

        # Skip TOC generation for non-Markdown formats
        if not self.toc_generator:
            return content

        # Check if TOC markers exist
        if self.toc_start_marker not in content or self.toc_end_marker not in content:
            return content

        # Extract content between MAIN markers to generate TOC from
        main_content = self._extract_main_content(content)

        # Detect bullet style from content outside the managed sections
        external_content = self._extract_external_content(content)
        if external_content and not self.toc_generator.bullet_style:
            detected_style = self.toc_generator._detect_bullet_style(external_content)
            self.toc_generator.bullet_style = detected_style

        # Generate TOC only from the main content (generated by the tool)
        toc_content = self.toc_generator.generate_toc(main_content)

        # Update TOC section
        return self._replace_between_markers(
            content, toc_content, self.toc_start_marker, self.toc_end_marker
        )

    def _update_tocfull_section(self, content: str) -> str:
        """Update TOC-FULL section if markers are present.

        Unlike the regular TOC (which indexes only the DocSmith-managed
        MAIN content), TOC-FULL lists all headings of the whole document,
        including hand-written ones. Headings with an explicit anchor
        (like ``<a id="..."></a>``) are linked exactly; anchors of other
        headings are derived from the heading text.
        """
        if not self.toc_generator:
            return content

        if (
            self.tocfull_start_marker not in content
            or self.tocfull_end_marker not in content
        ):
            return content

        # Detect bullet style from content outside the managed sections
        external_content = self._extract_external_content(content)
        if external_content and not self.toc_generator.bullet_style:
            detected_style = self.toc_generator._detect_bullet_style(external_content)
            self.toc_generator.bullet_style = detected_style

        # The whole document is the input; the old TOC/TOC-FULL sections
        # contain only list items (no headings), so they cannot pollute
        # the result
        toc_content = self.toc_generator.generate_toc(content)

        return self._replace_between_markers(
            content, toc_content, self.tocfull_start_marker, self.tocfull_end_marker
        )

    def _extract_main_content(self, content: str) -> str:
        """Extract content between MAIN markers for TOC generation."""
        if self.start_marker not in content or self.end_marker not in content:
            return ""

        # Extract content between main markers using regex
        pattern = f"{re.escape(self.start_marker)}(.*?){re.escape(self.end_marker)}"
        match = re.search(pattern, content, flags=re.DOTALL)

        if match:
            return match.group(1).strip()

        return ""

    def _extract_external_content(self, content: str) -> str:
        """Extract content outside MAIN and TOC markers for bullet style detection."""
        # Remove content between MAIN markers
        if self.start_marker in content and self.end_marker in content:
            pattern = f"{re.escape(self.start_marker)}.*?{re.escape(self.end_marker)}"
            content = re.sub(pattern, "", content, flags=re.DOTALL)

        # Remove content between TOC markers
        if self.toc_start_marker in content and self.toc_end_marker in content:
            pattern = (
                f"{re.escape(self.toc_start_marker)}.*?{re.escape(self.toc_end_marker)}"
            )
            content = re.sub(pattern, "", content, flags=re.DOTALL)

        # Remove content between TOC-FULL markers
        if self.tocfull_start_marker in content and self.tocfull_end_marker in content:
            pattern = (
                f"{re.escape(self.tocfull_start_marker)}"
                f".*?{re.escape(self.tocfull_end_marker)}"
            )
            content = re.sub(pattern, "", content, flags=re.DOTALL)

        return content.strip()

    def _create_new_readme(self, role_content: str, role_name: str) -> str:
        """Create a new README with basic template."""
        if self.format_type == "rst":
            return f"""Ansible role: {role_name}
{"=" * (15 + len(role_name))}

FIXME Add role description here.

{self.start_marker}
{role_content}
{self.end_marker}


Dependencies
============

See ``dependencies`` in ``meta/main.yml``.


Compatibility
=============

See ``min_ansible_version`` in ``meta/main.yml``.


Licensing, copyright
====================

.. REUSE-IgnoreStart
Copyright (c) [FIXME YYYY Your Name]

[FIXME Adapt license:
This project is licensed under the GNU General Public License v3.0 or later
(SPDX-License-Identifier: ``GPL-3.0-or-later``)].
.. REUSE-IgnoreEnd


Author information
==================

This project was created and is maintained by [FIXME Your Name].

"""
        else:
            return f"""# Ansible role: `{role_name}`

FIXME Add role description here.

{self.start_marker}
{role_content}
{self.end_marker}


## Dependencies<a id="dependencies"></a>

See `dependencies` in [`meta/main.yml`](./meta/main.yml).


## Compatibility<a id="compatibility"></a>

See `min_ansible_version` in [`meta/main.yml`](./meta/main.yml).


## Licensing, copyright<a id="licensing-copyright"></a>

<!--REUSE-IgnoreStart-->
Copyright (c) [FIXME YYYY Your Name]

[FIXME Adapt license:
This project is licensed under the GNU General Public License v3.0 or later
(SPDX-License-Identifier: `GPL-3.0-or-later`)].
<!--REUSE-IgnoreEnd-->


## Author information

This project was created and is maintained by [FIXME Your Name].

"""
